# Generated by Django 3.0.1 on 2019-12-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_auto_20191223_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='is_active',
        ),
        migrations.AddField(
            model_name='purchase',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
