# Generated by Django 3.0.1 on 2019-12-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_auto_20191223_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
